name: Protocol Tests
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'protocol/**'

jobs:
  e2eTest:
    name: Hardhat Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn compile
        working-directory: protocol
      - run: yarn test
        working-directory: protocol
        env:
          TESTS_MAINNET_RPC_URL: ${{ secrets.TESTS_MAINNET_RPC_URL }}
  fuzzTest:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # weird bug with forge needing to be built twice
      - run: forge install
        working-directory: protocol

      - run: forge test -vvvv --gas-report --fork-url https://rpc.ankr.com/eth
        working-directory: protocol
